services:
  db:
    image: mysql:5.7
    container_name: wordpress_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal

  wordpress1: &wp
    image: wordpress:latest
    container_name: wordpress1
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - db
    volumes:
      - ./shared_html:/var/www/html
    networks:
      - internal

  wordpress2:
    <<: *wp
    container_name: wordpress2

  wordpress3:
    <<: *wp
    container_name: wordpress3

  nginx:
    image: nginx:latest
    container_name: nginx_balancer
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./shared_html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - wordpress1
      - wordpress2
      - wordpress3
    networks:
      - internal

  locust:
    build:
      context: ./locust
    container_name: locust
    restart: unless-stopped
    working_dir: /mnt/locust
    volumes:
      - ./locust:/mnt/locust
    environment:
      LOCUST_FILE: "/mnt/locust/locustfile.py"
      ATTACKED_HOST: "http://nginx"
      LOCUST_OPTS: "--csv=/mnt/locust/results/run"
    entrypoint:
      - sh
      - -c
      - |
        locust \
          -f "$$LOCUST_FILE" \
          --host="$$ATTACKED_HOST" \
          $$LOCUST_OPTS
    ports:
      - "8089:8089"
    networks:
      - internal

volumes:
  db_data:

networks:
  internal:
    driver: bridge
